version: "3.8"
services:
  mongocontainer:
    image: mongo:latest
    container_name: mongocontainer
    ports:
      - 27017:27017

  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 8092:8092
    links:
      - mongocontainer



#services:
#  employeeservice:
#    build: ../../..
#    restart: always
#    ports:
#      - 8092:8092
#    depends_on:
#      - mongocontainer
#    links:
#      - mongocontainer
#
#  mongocontainer:
#    image: "mongo:latest"
#    container_name: "mongocontainer"
#    ports:
#      - 27017-27017



